### ISSUE TITLE
Add version property to composer.json

### ISSUE THREAD

**Issue by lallybrooky** [Ingenico-ePayments/connect-sdk-php#1]
When trying to add the package to my project via composer, it gives an error:

[InvalidArgumentException] Could not find package Ingenico-ePayments/connect-sdk-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

This could be due to a missing property in the composer.json schema, the `version` property. As the last commit states that there's been a `1.0.0` release, perhaps this was overlooked?

**Comment by rob-spoor** [comment]
If you check the composer.json file for release 1.0.0, you'll see that the name is not Ingenico-ePayments/connect-sdk-php but globalcollect/connect-sdk-php. Have you tried that one as well?

**Comment by rob-spoor** [comment]
Version 2.0.0 has been released today. This changes the name to `ingenico-epayments/connect-sdk-php`.

**Comment by kasperhendriks** [comment]
If composer has trouble locating the package, you can add to your root:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:Ingenico-ePayments/connect-sdk-php.git"
        }
```

**Comment by aadmathijssen** [comment]
Recently, the library has been registered on [Packagist](https://packagist.org/packages/ingenico-epayments/connect-sdk-php), and can be added to your own project as follows:

```
composer require ingenico-epayments/connect-sdk-php
```

The workaround for adding a VCS repository should not be necessary anymore.
