### ISSUE TITLE
what's the difference between /src and /lib, and which one should i used? 

### ISSUE THREAD

**Issue by jocky4012** [Ingenico-ePayments/connect-sdk-php#11]
As the title mentioned，which folder should  included in my project? All files in the two folder has the same namespace, i am sorry that i don't know how to use ,please give me your help, thanks

**Comment by rob-spoor** [comment]
You should include both folders. The `/src` folder contains the client, request and response classes, and is generated. The '/lib' folder contains manually written framework classes.
