### ISSUE TITLE
UnexpectedValueException in ResponseFactory after updateToken call.

### ISSUE THREAD

**Issue by hanken** [Ingenico-ePayments/connect-sdk-php#12]
Hi

If the $client->merchant()->tokens()->update() method is used. The server responses with a 204 and no Content-Type header. ResponseFactory requires a Conent-Type of application/json and hence throws an UnexpectedValueException (https://github.com/Ingenico-ePayments/connect-sdk-php/blob/master/lib/Ingenico/Connect/Sdk/ResponseFactory.php#L63).

Still happens after updating to the 5.34.0 release.

**Comment by rob-spoor** [comment]
Thanks for reporting this. This was an oversight that was already planned to be fixed. We moved the fix forward - for 204 responses, the content type is no longer required.
