### ISSUE TITLE
Cvv Capture issue

### ISSUE THREAD

**Issue by emranch31** [Ingenico-ePayments/connect-sdk-php#4]
I want to ask is there any way that I don't have to enter CVV again and again for payments

I know for recurring payment there is no need to enter CVV again, but I am using the one-off method.

If there is no recurring time define and if it can consider every recurring payment as separate payment, maybe I can use recurring instead of one-off just to get rid of CVV issue 

please can someone clarify

**Comment by rikvanthof** [comment]
It is possible to configure an account to not mark the CVV field as required, but this is not compliant and requires a waiver to be granted. This is then something that needs to be configured on our side (you can't do that yourself). Sandbox accounts all have the same default configuration to let you experiment with the API and SDKs, such configuration isn't possible on that environment. 

Please note that without the CVV for non-recurring transactions you will see reduced approval rates for your transactions. This is also not considered to be compliant. Marking transactions as recurring while the consumer is performing the checkout is also not considered to be compliant.

**Comment by emranch31** [comment]
great... thanx
