### ISSUE TITLE
InMemorySecretKeyStore::storeSecretKey() will throw UnexpectedValueException - not found class

### ISSUE THREAD

**Issue by bubnov-mikhail** [Ingenico-ePayments/connect-sdk-php#8]
Hello!

In the method you are throwing this exception, but you don't prefix the class with '\'
and you are not 'use UnexpectedValueException'.

This results in a php error in case if I provide a wrong $key or $secret

**Comment by rob-spoor** [comment]
Thanks for informing us, we will provide a fix at some later time. In the mean time you can prevent this error by not providing an empty key or secret.

**Comment by rob-spoor** [comment]
This has been fixed in version 5.19.0.
