### ISSUE TITLE
Hosted Checkout redirectUrl results in connection timeout

### ISSUE THREAD

**Issue by internetztube** [Ingenico-ePayments/connect-sdk-php#9]
I'm currently working on a very basic hosted checkout. The creation of the redirect url works just fine. The problem is, that the web server behind that redirect url does not respond in time. I'm getting a connection timeout. 

I think that the problem is probably not due to my code, nevertheless here is the script.
```
<?php

require __DIR__ . "/../vendor/autoload.php";

use Ingenico\Connect\Sdk\Domain\Hostedcheckout\Definitions\HostedCheckoutSpecificInput;
use Ingenico\Connect\Sdk\Domain\Definitions\AmountOfMoney;
use Ingenico\Connect\Sdk\Domain\Definitions\Address;
use Ingenico\Connect\Sdk\Domain\Payment\Definitions\Customer;
use Ingenico\Connect\Sdk\Domain\Payment\Definitions\Order;
use Ingenico\Connect\Sdk\Domain\Hostedcheckout\CreateHostedCheckoutRequest;
use Ingenico\Connect\Sdk\CommunicatorConfiguration;
use Ingenico\Connect\Sdk\DefaultConnection;
use Ingenico\Connect\Sdk\Communicator;
use Ingenico\Connect\Sdk\Client;

$apiKeyId = "{{ apikey }}";
$apiSecret = "{{ api secret }}";
$baseUrl = "https://eu.sandbox.api-ingenico.com";

$communicatorConfiguration = new CommunicatorConfiguration($apiKeyId, $apiSecret, $baseUrl, 'Integrator');
$connection = new DefaultConnection();
$communicator = new Communicator($connection, $communicatorConfiguration);

$client = new Client($communicator);

$hostedCheckoutSpecificInput = new HostedCheckoutSpecificInput();
$hostedCheckoutSpecificInput->locale = "en_GB";
$hostedCheckoutSpecificInput->variant = "testVariant";

$amountOfMoney = new AmountOfMoney();
$amountOfMoney->amount = 2345;
$amountOfMoney->currencyCode = "USD";

$billingAddress = new Address();
$billingAddress->countryCode = "US";

$customer = new Customer();
$customer->billingAddress = $billingAddress;
$customer->merchantCustomerId = 234234;

$order = new Order();
$order->amountOfMoney = $amountOfMoney;
$order->customer = $customer;

$body = new CreateHostedCheckoutRequest();
$body->hostedCheckoutSpecificInput = $hostedCheckoutSpecificInput;
$body->order = $order;


/** @var CreateHostedCheckoutRequest $response */
$response = $client->merchant({{ merchantId }})->hostedcheckouts()->create($body);

$foo = $response;
print_r($foo);
```

Response: 
```
Ingenico\Connect\Sdk\Domain\Hostedcheckout\CreateHostedCheckoutResponse Object
(
    [RETURNMAC] => hash1
    [hostedCheckoutId] => hash2
    [invalidTokens] => 
    [partialRedirectUrl] => pay1.sandbox.secured-by-ingenico.com/checkout/hash3:hash2:hash4?requestToken=hash5
)

```
<img width="1029" alt="bildschirmfoto 2018-05-02 um 10 54 26" src="https://user-images.githubusercontent.com/6382364/39514412-592ce3ee-4df7-11e8-8ed6-f6b7c4e849f9.png">
<img width="1029" alt="bildschirmfoto 2018-05-02 um 10 54 24" src="https://user-images.githubusercontent.com/6382364/39514418-5b3a3db2-4df7-11e8-96ca-4973fe6718c0.png">

**Comment by rob-spoor** [comment]
It's not your code, it appears to be an issue with the infrastructure. I've escalated this to the correct people.

**Comment by rob-spoor** [comment]
We think that you forgot to add the https:// prefix and your subdomain. Can you make sure you add these before redirecting? Remember that the response gives a _partial_ redirect URL, you must add https:// and your own subdomain yourself.

**Comment by internetztube** [comment]
Well ...
<img width="899" alt="bildschirmfoto 2018-05-02 um 14 05 16" src="https://user-images.githubusercontent.com/6382364/39522214-0596755e-4e12-11e8-9a23-8689c732c5a3.png">

**Comment by ronaldmiddelkoop** [comment]
Hi internetztube, looks like you've added https, but not your merchant's subdomain. You can request your own subdomain using the configuration center, but you can also always use _payment_.

So, your URL would be https://payment.pay1.sandbox.secured-by-ingenico.com/checkout/...

**Comment by falloutxxx2** [comment]
https://+Subdomains+partialRedirectUrl 

I also met this problem, I really want to swear.(this way is really easy to confuse)
